    schemaVersion: 1.0.0
    locale: en
    title: Static Website Deployment Pipeline Stack

    variableGroups:
    - title: Source Configuration
      variables:
      - tenancy_ocid
      - release
      - region
      - compartment_ocid
    - title: Site Configuration
      variables:
      - root_domain_name
      - root_domain_ttl

    variables:

      compartment_ocid:
        type: oci:identity:compartment:id
        required: true
        visible: true
        title: ${Messages.solutionsHub.solutions.stravaQuickstarts.variables.compartmentTitle()}
        description: ${Messages.solutionsHub.solutions.stravaQuickstarts.variables.compartmentDescription()}

    outputs:

      dashboard_url:
        title: ${Messages.solutionsHub.solutions.stravaQuickstarts.outputs.dashboardUrlTitle()}
        displayText: ${Messages.solutionsHub.solutions.stravaQuickstarts.outputs.dashboardUrlDisplayText()}
        type: link
        visible: true

      adb_password:
        title: ${Messages.solutionsHub.solutions.stravaQuickstarts.outputs.adbPasswordTitle()}
        displayText: ${Messages.solutionsHub.solutions.stravaQuickstarts.outputs.adbPasswordTitle()}
        visible: true
        sensitive: true

    primaryOutputButton: dashboard_url
